name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.WAXAM140 }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AKIARXO4UZOB6GVYMGML }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.65xh42e5o8bR/2Y/CQ/q/IPQ8thmPcruci6ti1b0 }}
        AWS_REGION: 'us-east-1'   
        SOURCE_DIR: 'public'      

    -uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: ${{ secrets.E30O700258GUGO }}
        PATHS: '/*'
        AWS_REGION: 'ap-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AKIARXO4UZOB6GVYMGML }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.65xh42e5o8bR/2Y/CQ/q/IPQ8thmPcruci6ti1b0 }}
